phrase:
  project_id: febdcb5f64fbc56e310d2e74415dbd15
  file_format: yml
  
  push:
    sources:
    - file: en.yml
      params:
        locale_id: en
        update_translations: true
        autotranslate: true
  pull:
    targets:
    - file: de.yml
      params:
        locale_id: de
