phrase:
  project_id: 1a6b899f1802961a7a7a3d7f4b3be74e
  file_format: json
  
  push:
    sources:
    - file: sample key file.json
      params:
        locale_id: en
        update_translations: true
        autotranslate: true
  pull:
    targets:
    - file: sample key file.json
      params:
        locale_id: de
